from typing import TypedDict, List, Dict, Set
from enum import Enum
from BaseClasses import Item, ItemClassification
from .Locations import location_table, event_table


class RE5Type(Enum):
    Chapter = 0
    Key = 1
    Explosive = 2
    Special = 3
    Assault = 4
    Magnum = 5
    Handgun = 6
    SMG = 7
    Shotgun = 8
    Rifle = 9
    Treasure = 10
    Healing = 11
    Ammo = 12
    Filler = 13


class ItemDict(TypedDict, total=False):
    name: str
    type: RE5Type
    xml_id: int
    ap_id: int


base_id = 3618000


item_table: List[ItemDict] = [
    # Weapons
    {'name': "Beretta M92F",
         'type': RE5Type.Handgun,
         'xml_id': 258,
         'ap_id': 3618001},
    {'name': "M93R",
         'type': RE5Type.Handgun,
         'xml_id': 286,
         'ap_id': 3618002},
    {'name': "Ithaca 37",
         'type': RE5Type.Shotgun,
         'xml_id': 260,
         'ap_id': 3618003},
    {'name': "Benelli M3",
         'type': RE5Type.Shotgun,
         'xml_id': 278,
         'ap_id': 3618004},
    {'name': "Jailbreaker",
         'type': RE5Type.Shotgun,
         'xml_id': 279,
         'ap_id': 3618005},
    {'name': "VZ61",
         'type': RE5Type.SMG,
         'xml_id': 259,
         'ap_id': 3618006},
    {'name': "AK-74",
         'type': RE5Type.Assault,
         'xml_id': 285,
         'ap_id': 3618007},
    {'name': "H&K MP5",
         'type': RE5Type.SMG,
         'xml_id': 275,
         'ap_id': 3618008},
    {'name': "SIG 556",
         'type': RE5Type.Assault,
         'xml_id': 265,
         'ap_id': 3618009},
    {'name': "S75",
         'type': RE5Type.Rifle,
         'xml_id': 261,
         'ap_id': 3618010},
    {'name': "SVD Dragunov",
         'type': RE5Type.Rifle,
         'xml_id': 288,
         'ap_id': 3618011},
    {'name': "H&K PSG-1",
         'type': RE5Type.Rifle,
         'xml_id': 284,
         'ap_id': 3618012},
    {'name': "S&W M29",
         'type': RE5Type.Magnum,
         'xml_id': 267,
         'ap_id': 3618013},
    {'name': "S&W M500",
         'type': RE5Type.Magnum,
         'xml_id': 283,
         'ap_id': 3618014},
    {'name': "L. Hawk",
         'type': RE5Type.Magnum,
         'xml_id': 282,
         'ap_id': 3618015},
    {'name': "M40 GL",
         'type': RE5Type.Explosive,
         'xml_id': 268,
         'ap_id': 3618016},
    {'name': "Rocket Launcher",
         'type': RE5Type.Explosive,
         'xml_id': 269,
         'ap_id': 3618017},
    {'name': "Samurai's Edge",
         'type': RE5Type.Handgun,
         'xml_id': 297,
         'ap_id': 3618018},
    {'name': "Hydra",
         'type': RE5Type.Shotgun,
         'xml_id': 281,
         'ap_id': 3618019},
    {'name': "Minigun",
         'type': RE5Type.Special,
         'xml_id': 277,
         'ap_id': 3618020},
    {'name': "Longbow",
         'type': RE5Type.Special,
         'xml_id': 271,
         'ap_id': 3618021},
    # Keys
    {'name': "Furnace Key",
         'type': RE5Type.Key,
         'xml_id': 1283,
         'ap_id': 3618022},
    {'name': "Port Key",
         'type': RE5Type.Key,
         'xml_id': 1286,
         'ap_id': 3618023},
    {'name': "Hangar Keycard A",
         'type': RE5Type.Key,
         'xml_id': 1287,
         'ap_id': 3618024},
    {'name': "Hangar Keycard B",
         'type': RE5Type.Key,
         'xml_id': 1288,
         'ap_id': 3618025},
    {'name': "Old Building Key",
         'type': RE5Type.Key,
         'xml_id': 1289,
         'ap_id': 3618026},
    {'name': "Tanker Keycard A",
         'type': RE5Type.Key,
         'xml_id': 1290,
         'ap_id': 3618027},
    {'name': "Tanker Keycard B",
         'type': RE5Type.Key,
         'xml_id': 1303,
         'ap_id': 3618028},
    {'name': "Sky Emblem",
         'type': RE5Type.Key,
         'xml_id': 1294,
         'ap_id': 3618029},
    {'name': "Earth Emblem",
         'type': RE5Type.Key,
         'xml_id': 1295,
         'ap_id': 3618030},
    {'name': "Sea Emblem",
         'type': RE5Type.Key,
         'xml_id': 1296,
         'ap_id': 3618031},
    {'name': "Shaman Slate",
         'type': RE5Type.Key,
         'xml_id': 1298,
         'ap_id': 3618032},
    {'name': "Warrior Slate",
         'type': RE5Type.Key,
         'xml_id': 1299,
         'ap_id': 3618033},
    {'name': "Beast Slate",
         'type': RE5Type.Key,
         'xml_id': 1300,
         'ap_id': 3618034},
    {'name': "Raptor Slate",
         'type': RE5Type.Key,
         'xml_id': 1301,
         'ap_id': 3618035},
    {'name': "Bridge Keycard",
         'type': RE5Type.Key,
         'xml_id': 1307,
         'ap_id': 3618036},
    {'name': "Crane Keycard",
         'type': RE5Type.Key,
         'xml_id': 1302,
         'ap_id': 3618037},
    {'name': "Guard's Key",
         'type': RE5Type.Key,
         'xml_id': 1306,
         'ap_id': 3618038},
    # Chapters
    # XML ID should be ignored by the Arc Randomizer, and instead place a dummy item in the location (invisible item from lost in nightmares?)
    # Location itself should be watched via memory to unlock chapter on the save.
    {'name': "Chapter 1-1",
         'type': RE5Type.Chapter,
         'xml_id': -11,
         'ap_id': 3622011},
    {'name': "Chapter 1-2",
         'type': RE5Type.Chapter,
         'xml_id': -12,
         'ap_id': 3622012},
    {'name': "Chapter 2-1",
         'type': RE5Type.Chapter,
         'xml_id': -21,
         'ap_id': 3622021},
    {'name': "Chapter 2-2",
         'type': RE5Type.Chapter,
         'xml_id': -22,
         'ap_id': 3622022},
    {'name': "Chapter 2-3",
         'type': RE5Type.Chapter,
         'xml_id': -23,
         'ap_id': 3622023},
    {'name': "Chapter 3-1",
         'type': RE5Type.Chapter,
         'xml_id': -31,
         'ap_id': 3622031},
    {'name': "Chapter 3-2",
         'type': RE5Type.Chapter,
         'xml_id': -32,
         'ap_id': 3622032},
    {'name': "Chapter 3-3",
         'type': RE5Type.Chapter,
         'xml_id': -33,
         'ap_id': 3622033},
    {'name': "Chapter 4-1",
         'type': RE5Type.Chapter,
         'xml_id': -41,
         'ap_id': 3622041},
    {'name': "Chapter 4-2",
         'type': RE5Type.Chapter,
         'xml_id': -42,
         'ap_id': 3622042},
    {'name': "Chapter 5-1",
         'type': RE5Type.Chapter,
         'xml_id': -51,
         'ap_id': 3622051},
    {'name': "Chapter 5-2",
         'type': RE5Type.Chapter,
         'xml_id': -52,
         'ap_id': 3622052},
    {'name': "Chapter 5-3",
         'type': RE5Type.Chapter,
         'xml_id': -53,
         'ap_id': 3622053},
    {'name': "Chapter 6-1",
         'type': RE5Type.Chapter,
         'xml_id': -61,
         'ap_id': 3622061},
    {'name': "Chapter 6-2",
         'type': RE5Type.Chapter,
         'xml_id': -62,
         'ap_id': 3622062},
    {'name': "Chapter 6-3",
         'type': RE5Type.Chapter,
         'xml_id': -63,
         'ap_id': 3622063},
    # Filler - Ammo, Herbs, Gold, etc
    {'name': "Handgun Ammo",
         'type': RE5Type.Filler,
         'xml_id': 513,
         'ap_id': 3619001},
    {'name': "Machinegun Ammo",
         'type': RE5Type.Filler,
         'xml_id': 514,
         'ap_id': 3619002},
    {'name': "Shotgun Ammo",
         'type': RE5Type.Filler,
         'xml_id': 515,
         'ap_id': 3619003},
    {'name': "Rifle Ammo",
         'type': RE5Type.Filler,
         'xml_id': 516,
         'ap_id': 3619004},
    {'name': "Explosive Rounds",
         'type': RE5Type.Filler,
         'xml_id': 293,
         'ap_id': 3619005},
    {'name': "Acid Rounds",
         'type': RE5Type.Filler,
         'xml_id': 294,
         'ap_id': 3619006},
    {'name': "Ice Rounds",
         'type': RE5Type.Filler,
         'xml_id': 295,
         'ap_id': 3619007},
    {'name': "Flame Rounds",
         'type': RE5Type.Filler,
         'xml_id': 313,
         'ap_id': 3619008},
    {'name': "Flash Rounds",
         'type': RE5Type.Filler,
         'xml_id': 314,
         'ap_id': 3619009},
    {'name': "Electric Rounds",
         'type': RE5Type.Filler,
         'xml_id': 315,
         'ap_id': 3619010},
    {'name': "Magnum Ammo",
         'type': RE5Type.Filler,
         'xml_id': 521,
         'ap_id': 3619011},
    {'name': "Green Herb",
         'type': RE5Type.Healing,
         'xml_id': 769,
         'ap_id': 3619012},
    {'name': "Red Herb",
         'type': RE5Type.Filler,
         'xml_id': 770,
         'ap_id': 3619013},
    {'name': "First Aid Spray",
         'type': RE5Type.Healing,
         'xml_id': 772,
         'ap_id': 3619014},
    {'name': "G+G Herb",
         'type': RE5Type.Healing,
         'xml_id': 775,
         'ap_id': 3619015},
    {'name': "G+R Herb",
         'type': RE5Type.Healing,
         'xml_id': 777,
         'ap_id': 3619016},
    {'name': "Melee Vest",
         'type': RE5Type.Filler,
         'xml_id': 1537,
         'ap_id': 3619017},
    {'name': "Bulletproof Vest",
         'type': RE5Type.Filler,
         'xml_id': 1542,
         'ap_id': 3619018},
    {'name': "White Egg",
         'type': RE5Type.Filler,
         'xml_id': 316,
         'ap_id': 3619019},
    {'name': "Brown Egg",
         'type': RE5Type.Filler,
         'xml_id': 317,
         'ap_id': 3619020},
    {'name': "Golden Egg",
         'type': RE5Type.Filler,
         'xml_id': 318,
         'ap_id': 3619021},
    {'name': "Rotten Egg",
         'type': RE5Type.Filler,
         'xml_id': 310,
         'ap_id': 3619022},
    {'name': "Hand Grenade",
         'type': RE5Type.Explosive,
         'xml_id': 262,
         'ap_id': 3619023},
    {'name': "Incendiary Grenade",
         'type': RE5Type.Filler,
         'xml_id': 263,
         'ap_id': 3619024},
    {'name': "Flash Grenade",
         'type': RE5Type.Filler,
         'xml_id': 264,
         'ap_id': 3619025},
    {'name': "Large Gold",
         'type': RE5Type.Filler,
         'xml_id': 1025,
         'ap_id': 3619026},
    {'name': "Small Gold",
         'type': RE5Type.Filler,
         'xml_id': 1026,
         'ap_id': 3619027},
    {'name': "H&K P8",
         'type': RE5Type.Handgun,
         'xml_id': 272,
         'ap_id': 3619028},
    {'name': "SIG P226",
         'type': RE5Type.Handgun,
         'xml_id': 273,
         'ap_id': 3619029},
]

group_table: Dict[str, Set[str]] = {
    "weapons": {"Beretta M92F",
                "H&K P8",
                "SIG P226",
                "M93R",
                "Ithaca 37",
                "Benelli M3",
                "Jailbreaker",
                "VZ61",
                "AK-74",
                "H&K MP5",
                "SIG 556",
                "S75",
                "SVD Dragunov",
                "H&K PSG-1",
                "S&W M29",
                "S&W M500",
                "L. Hawk",
                "M40 GL",
                "Rocket Launcher",
                "Samurai's Edge",
                "Hydra",
                "Minigun",
                "Longbow"},
    "pistol": {"Beretta M92F",
                "Samurai's Edge",
                "H&K P8",
                "SIG P226",
                "M93R"},
    "precise": {"Beretta M92F",
                "Samurai's Edge",
                "H&K P8",
                "SIG P226",
                "S75",
                "SVD Dragunov",
                "H&K PSG-1",
                "S&W M29",
                "S&W M500",
                "L. Hawk",
                "Longbow"},
   "heavywep": {"Ithaca 37",
                "Benelli M3",
                "Jailbreaker",
                "S&W M29",
                "S&W M500",
                "L. Hawk",
                "M40 GL",
                "Rocket Launcher",
                "Hydra",
                "Minigun",
                "Longbow"},
       "keys": {"Furnace Key",
                "Port Key",
                "Hangar Keycard A",
                "Hangar Keycard B",
                "Old Building Key",
                "Tanker Keycard A",
                "Tanker Keycard B",
                "Sky Emblem",
                "Earth Emblem",
                "Sea Emblem",
                "Shaman Slate",
                "Warrior Slate",
                "Beast Slate",
                "Raptor Slate",
                "Bridge Keycard",
                "Crane Keycard",
                "Guard's Key"},
     "slates": {"Shaman Slate",
                "Warrior Slate",
                "Beast Slate",
                "Raptor Slate"},
    "emblems": {"Sky Emblem",
                "Earth Emblem",
                "Sea Emblem"},
   "keycards": {"Hangar Keycard A",
                "Hangar Keycard B",    
                "Tanker Keycard A",
                "Tanker Keycard B",
                "Bridge Keycard",
                "Crane Keycard"},
   "chapters": {"Chapter 1-1",
                "Chapter 1-2",
                "Chapter 2-1",
                "Chapter 2-2",
                "Chapter 2-3",
                "Chapter 3-1",
                "Chapter 3-2",
                "Chapter 3-3",
                "Chapter 4-1",
                "Chapter 4-2",
                "Chapter 5-1",
                "Chapter 5-2",
                "Chapter 5-3",
                "Chapter 6-1",
                "Chapter 6-2",
                "Chapter 6-3"},
       "ammo": {"Handgun Ammo",
                "Machinegun Ammo",
                "Shotgun Ammo",
                "Rifle Ammo",
                "Explosive Rounds",
                "Acid Rounds",
                "Ice Rounds",
                "Flame Rounds",
                "Flash Rounds",
                "Electric Rounds",
                "Magnum Ammo"},
   "grenades": {"Flash Grenade",
                "Incendiary Grenade",
                "Hand Grenade",
                "Rotten Egg"},
    "healing": {"Green Herb",
                "Red Herb",
                "First Aid Spray",
                "G+G Herb",
                "G+R Herb",
                "White Egg",
                "Brown Egg",
                "Golden Egg"},
     "filler": {"Handgun Ammo",
                "Machinegun Ammo",
                "Shotgun Ammo",
                "Rifle Ammo",
                "Explosive Rounds",
                "Acid Rounds",
                "Ice Rounds",
                "Flame Rounds",
                "Flash Rounds",
                "Electric Rounds",
                "Magnum Ammo",
                "Flash Grenade",
                "Incendiary Grenade",
                "Hand Grenade",
                "Rotten Egg",
                "Green Herb",
                "Red Herb",
                "First Aid Spray",
                "G+G Herb",
                "G+R Herb",
                "White Egg",
                "Brown Egg",
                "Golden Egg"},
}
