from typing import TypedDict, List, Dict, Set
from enum import Enum


class RE5Type(Enum):
    Chapter = 0
    Key = 1
    Assault = 2
    Magnum = 3
    Explosive = 4
    Special = 5
    Treasure = 6
    Handgun = 7
    SMG = 8
    Shotgun = 9
    Rifle = 10
    Healing = 11
    Ammo = 12
    Filler = 13


class ItemDict(TypedDict, total=False):
    name: str
    type: RE5Type
    xml_id: int


base_id = 3618000


item_table: List[ItemDict] = [
    # Weapons
    {'name': "Victory",
        'type': RE5Type.Key,
        'xml_id': 006900},
    {'name': "Beretta M92F",
        'type': RE5Type.Handgun,
        'xml_id': 258},
    {'name': "M93R",
        'type': RE5Type.Handgun,
        'xml_id': 286},
    {'name': "Ithaca 37",
        'type': RE5Type.Shotgun,
        'xml_id': 260},
    {'name': "Benelli M3",
        'type': RE5Type.Shotgun,
        'xml_id': 278},
    {'name': "Jailbreaker",
        'type': RE5Type.Shotgun,
        'xml_id': 279},
    {'name': "VZ61",
        'type': RE5Type.SMG,
        'xml_id': 259},
    {'name': "AK-74",
        'type': RE5Type.Assault,
        'xml_id': 285},
    {'name': "H&K MP5",
        'type': RE5Type.SMG,
        'xml_id': 275},
    {'name': "SIG 556",
        'type': RE5Type.Assault,
        'xml_id': 265},
    {'name': "S75",
        'type': RE5Type.Rifle,
        'xml_id': 261},
    {'name': "SVD Dragunov",
        'type': RE5Type.Rifle,
        'xml_id': 288},
    {'name': "H&K PSG-1",
        'type': RE5Type.Rifle,
        'xml_id': 284},
    {'name': "S&W M29",
        'type': RE5Type.Magnum,
        'xml_id': 267},
    {'name': "S&W M500",
        'type': RE5Type.Magnum,
        'xml_id': 283},
    {'name': "L. Hawk",
        'type': RE5Type.Magnum,
        'xml_id': 282},
    {'name': "M40 GL",
        'type': RE5Type.Explosive,
        'xml_id': 268},
    {'name': "Rocket Launcher",
        'type': RE5Type.Explosive,
        'xml_id': 269},
    {'name': "Samurai's Edge",
        'type': RE5Type.Handgun,
        'xml_id': 297},
    {'name': "Hydra",
        'type': RE5Type.Shotgun,
        'xml_id': 281},
    {'name': "Minigun",
        'type': RE5Type.Special,
        'xml_id': 277},
    {'name': "Longbow",
        'type': RE5Type.Special,
        'xml_id': 271},
    # Keys
    {'name': "Furnace Key",
        'type': RE5Type.Key,
        'xml_id': 1283},
    {'name': "Port Key",
         'type': RE5Type.Key,
         'xml_id': 1286},
    {'name': "Hangar Keycard A",
         'type': RE5Type.Key,
         'xml_id': 1287},
    {'name': "Hangar Keycard B",
         'type': RE5Type.Key,
         'xml_id': 1288},
    {'name': "Old Building Key",
         'type': RE5Type.Key,
         'xml_id': 1289},
    {'name': "Tanker Keycard A",
         'type': RE5Type.Key,
         'xml_id': 1290},
    {'name': "Tanker Keycard B",
         'type': RE5Type.Key,
         'xml_id': 1303},
    {'name': "Sky Emblem",
         'type': RE5Type.Key,
         'xml_id': 1294},
    {'name': "Earth Emblem",
         'type': RE5Type.Key,
         'xml_id': 1295},
    {'name': "Sea Emblem",
         'type': RE5Type.Key,
         'xml_id': 1296},
    {'name': "Shaman Slate",
         'type': RE5Type.Key,
         'xml_id': 1298},
    {'name': "Warrior Slate",
         'type': RE5Type.Key,
         'xml_id': 1299},
    {'name': "Beast Slate",
         'type': RE5Type.Key,
         'xml_id': 1300},
    {'name': "Raptor Slate",
         'type': RE5Type.Key,
         'xml_id': 1301},
    {'name': "Bridge Keycard",
         'type': RE5Type.Key,
         'xml_id': 1307},
    {'name': "Crane Keycard",
         'type': RE5Type.Key,
         'xml_id': 1302},
    {'name': "Guard's Key",
         'type': RE5Type.Key,
         'xml_id': 1306},
    # Chapters
    # XML ID should be ignored by the Arc Randomizer, and instead a dummy item placed like gold.
    # Location itself should be watched via memory to unlock chapter on the save.
    {'name': "Chapter 1-1",
         'type': RE5Type.Chapter,
         'xml_id': 00011},
    {'name': "Chapter 1-2",
         'type': RE5Type.Chapter,
         'xml_id': 00012},
    {'name': "Chapter 2-1",
         'type': RE5Type.Chapter,
         'xml_id': 00021},
    {'name': "Chapter 2-2",
         'type': RE5Type.Chapter,
         'xml_id': 00023},
    {'name': "Chapter 2-3",
         'type': RE5Type.Chapter,
         'xml_id': 00023},
    {'name': "Chapter 3-1",
         'type': RE5Type.Chapter,
         'xml_id': 00031},
    {'name': "Chapter 3-2",
         'type': RE5Type.Chapter,
         'xml_id': 00032},
    {'name': "Chapter 3-3",
         'type': RE5Type.Chapter,
         'xml_id': 00033},
    {'name': "Chapter 4-1",
         'type': RE5Type.Chapter,
         'xml_id': 00041},
    {'name': "Chapter 4-2",
         'type': RE5Type.Chapter,
         'xml_id': 00042},
    {'name': "Chapter 5-1",
         'type': RE5Type.Chapter,
         'xml_id': 00051},
    {'name': "Chapter 5-2",
         'type': RE5Type.Chapter,
         'xml_id': 00052},
    {'name': "Chapter 5-3",
         'type': RE5Type.Chapter,
         'xml_id': 00053},
    {'name': "Chapter 6-1",
         'type': RE5Type.Chapter,
         'xml_id': 00061},
    {'name': "Chapter 6-2",
         'type': RE5Type.Chapter,
         'xml_id': 00062},
    {'name': "Chapter 6-3",
         'type': RE5Type.Chapter,
         'xml_id': 00063},
    # Filler - Ammo, Herbs, Gold, etc
    {'name': "Handgun Ammo",
         'type': RE5Type.Ammo,
         'xml_id': 513},
    {'name': "Machinegun Ammo",
         'type': RE5Type.Ammo,
         'xml_id': 514},
    {'name': "Shotgun Ammo",
         'type': RE5Type.Ammo,
         'xml_id': 515},
    {'name': "Rifle Ammo",
         'type': RE5Type.Ammo,
         'xml_id': 516},
    {'name': "Explosive Rounds",
         'type': RE5Type.Ammo,
         'xml_id': 293},
    {'name': "Acid Rounds",
         'type': RE5Type.Ammo,
         'xml_id': 294},
    {'name': "Ice Rounds",
         'type': RE5Type.Ammo,
         'xml_id': 295},
    {'name': "Flame Rounds",
         'type': RE5Type.Ammo,
         'xml_id': 313},
    {'name': "Flash Rounds",
         'type': RE5Type.Ammo,
         'xml_id': 314},
    {'name': "Electric Rounds",
         'type': RE5Type.Ammo,
         'xml_id': 315},
    {'name': "Magnum Ammo",
         'type': RE5Type.Ammo,
         'xml_id': 521},
    {'name': "Green Herb",
         'type': RE5Type.Healing,
         'xml_id': 769},
    {'name': "Red Herb",
         'type': RE5Type.Healing,
         'xml_id': 770},
    {'name': "First Aid Spray",
         'type': RE5Type.Healing,
         'xml_id': 772},
    {'name': "G+G Herb",
         'type': RE5Type.Healing,
         'xml_id': 775},
    {'name': "G+R Herb",
         'type': RE5Type.Healing,
         'xml_id': 777},
    {'name': "Melee Vest",
         'type': RE5Type.Filler,
         'xml_id': 1537},
    {'name': "Bulletproof Vest",
         'type': RE5Type.Filler,
         'xml_id': 1542},
    {'name': "White Egg",
         'type': RE5Type.Healing,
         'xml_id': 316},
    {'name': "Brown Egg",
         'type': RE5Type.Healing,
         'xml_id': 317},
    {'name': "Golden Egg",
         'type': RE5Type.Healing,
         'xml_id': 318},
    {'name': "Rotten Egg",
         'type': RE5Type.Filler,
         'xml_id': 310},
    {'name': "Hand Grenade",
         'type': RE5Type.Explosive,
         'xml_id': 262},
    {'name': "Incendiary Grenade",
         'type': RE5Type.Explosive,
         'xml_id': 263},
    {'name': "Flash Grenade",
         'type': RE5Type.Filler,
         'xml_id': 264},
]


group_table: Dict[str, Set[str]] = {
    "weapons": {"Beretta M92F",
                "M93R",
                "Ithaca 37",
                "Benelli M3",
                "Jailbreaker",
                "VZ61",
                "AK-74",
                "H&K MP5",
                "SIG 556",
                "S75",
                "SVD Dragunov",
                "H&K PSG-1",
                "S&W M29",
                "S&W M500",
                "L. Hawk",
                "M40 GL",
                "Rocket Launcher",
                "Samurai's Edge",
                "Hydra",
                "Minigun",
                "Longbow"},
       "keys": {"Furnace Key",
                "Port Key",
                "Hangar Keycard A",
                "Hangar Keycard B",
                "Old Building Key",
                "Tanker Keycard A",
                "Tanker Keycard B",
                "Sky Emblem",
                "Earth Emblem",
                "Sea Emblem",
                "Shaman Slate",
                "Warrior Slate",
                "Beast Slate",
                "Raptor Slate",
                "Bridge Keycard",
                "Crane Keycard",
                "Guard's Key"},
     "slates": {"Shaman Slate",
                "Warrior Slate",
                "Beast Slate",
                "Raptor Slate"},
    "emblems": {"Sky Emblem",
                "Earth Emblem",
                "Sea Emblem"},
   "keycards": {"Hangar Keycard A",
                "Hangar Keycard B",    
                "Tanker Keycard A",
                "Tanker Keycard B",
                "Bridge Keycard",
                "Crane Keycard"},
   "chapters": {"Chapter 1-1",
                "Chapter 1-2",
                "Chapter 2-1",
                "Chapter 2-2",
                "Chapter 2-3",
                "Chapter 3-1",
                "Chapter 3-2",
                "Chapter 3-3",
                "Chapter 4-1",
                "Chapter 4-2",
                "Chapter 5-1",
                "Chapter 5-2",
                "Chapter 5-3",
                "Chapter 6-1",
                "Chapter 6-2",
                "Chapter 6-3"},
       "ammo": {"Handgun Ammo",
                "Machinegun Ammo",
                "Shotgun Ammo",
                "Rifle Ammo",
                "Explosive Rounds",
                "Acid Rounds",
                "Ice Rounds",
                "Flame Rounds",
                "Flash Rounds",
                "Electric Rounds",
                "Magnum Ammo"},
   "grenades": {"Flash Grenade",
                "Incendiary Grenade",
                "Hand Grenade",
                "Rotten Egg"},
    "healing": {"Green Herb",
                "Red Herb",
                "First Aid Spray",
                "G+G Herb",
                "G+R Herb",
                "White Egg",
                "Brown Egg",
                "Golden Egg"},
}
