from typing import TypedDict, List, Dict, Set
from enum import Enum


class RE5Type(Enum):
    Chapter = 0
    Key = 1
    Assault = 2
    Magnum = 3
    Explosive = 4
    Special = 5
    Treasure = 6
    Handgun = 7
    SMG = 8
    Shotgun = 9
    Rifle = 10


class ItemDict(TypedDict, total=False):
    name: str
    count: int
    type: RE5Type
    xml_id: int


base_id = 3618000


item_table: List[ItemDict] = [
    # Weapons
    {'name': "Beretta M92F",
        'type': RE5Type.Handgun,
        'xml_id': 258},
    {'name': "M93R",
        'type': RE5Type.Handgun,
        'xml_id': 286},
    {'name': "Ithaca 37",
        'type': RE5Type.Shotgun,
        'xml_id': 260},
    {'name': "Benelli M3",
        'type': RE5Type.Shotgun,
        'xml_id': 278},
    {'name': "Jailbreaker",
        'type': RE5Type.Shotgun,
        'xml_id': 279},
    {'name': "VZ61",
        'type': RE5Type.SMG,
        'xml_id': 259},
    {'name': "AK-74",
        'type': RE5Type.Assault,
        'xml_id': 285},
    {'name': "H&K MP5",
        'type': RE5Type.SMG,
        'xml_id': 275},
    {'name': "SIG 556",
        'type': RE5Type.Assault,
        'xml_id': 265},
    {'name': "S75",
        'type': RE5Type.Rifle,
        'xml_id': 261},
    {'name': "SVD Dragunov",
        'type': RE5Type.Rifle,
        'xml_id': 288},
    {'name': "H&K PSG-1",
        'type': RE5Type.Rifle,
        'xml_id': 284},
    {'name': "S&W M29",
        'type': RE5Type.Magnum,
        'xml_id': 267},
    {'name': "S&W M500",
        'type': RE5Type.Magnum,
        'xml_id': 283},
    {'name': "L. Hawk",
        'type': RE5Type.Magnum,
        'xml_id': 282},
    {'name': "M40 GL",
        'type': RE5Type.Explosive,
        'xml_id': 268},
    {'name': "Rocket Launcher",
        'type': RE5Type.Explosive,
        'xml_id': 269},
    {'name': "Samurai's Edge",
        'type': RE5Type.Handgun,
        'xml_id': 297},
    {'name': "Hydra",
        'type': RE5Type.Shotgun,
        'xml_id': 281},
    {'name': "Minigun",
        'type': RE5Type.Special,
        'xml_id': 277},
    {'name': "Longbow",
        'type': RE5Type.Special,
        'xml_id': 271},
    # Keys
    {'name': "Furnace Key",
        'type': RE5Type.Key,
        'xml_id': 1283},
    {'name': "Port Key",
         'type': RE5Type.Key,
         'xml_id': 1286},
    {'name': "Hangar Keycard A",
         'type': RE5Type.Key,
         'xml_id': 1287},
    {'name': "Hangar Keycard B",
         'type': RE5Type.Key,
         'xml_id': 1288},
    {'name': "Old Building Key",
         'type': RE5Type.Key,
         'xml_id': 1289},
    {'name': "Tanker Keycard A",
         'type': RE5Type.Key,
         'xml_id': 1290},
    {'name': "Tanker Keycard B",
         'type': RE5Type.Key,
         'xml_id': 1303},
    {'name': "Sky Emblem",
         'type': RE5Type.Key,
         'xml_id': 1294},
    {'name': "Earth Emblem",
         'type': RE5Type.Key,
         'xml_id': 1295},
    {'name': "Sea Emblem",
         'type': RE5Type.Key,
         'xml_id': 1296},
    {'name': "Shaman Slate",
         'type': RE5Type.Key,
         'xml_id': 1298},
    {'name': "Warrior Slate",
         'type': RE5Type.Key,
         'xml_id': 1299},
    {'name': "Beast Slate",
         'type': RE5Type.Key,
         'xml_id': 1300},
    {'name': "Raptor Slate",
         'type': RE5Type.Key,
         'xml_id': 1301},
    {'name': "Crane Keycard",
         'type': RE5Type.Key,
         'xml_id': 1302},
    {'name': "Guard's Key",
         'type': RE5Type.Key,
         'xml_id': 1306},
]


group_table: Dict[str, Set[str]] = {
    "weapons": {"Beretta M92F",
                  "M93R",
                  "Ithaca 37",
                  "Benelli M3",
                  "Jailbreaker",
                  "VZ61",
                  "AK-74",
                  "H&K MP5",
                  "SIG 556",
                  "S75",
                  "SVD Dragunov",
                  "H&K PSG-1",
                  "S&W M29",
                  "S&W M500",
                  "L. Hawk",
                  "M40 GL",
                  "Rocket Launcher",
                  "Samurai's Edge",
                  "Hydra",
                  "Minigun",
                  "Longbow"},
         "keys": {"Furnace Key",
                  "Port Key",
                  "Hangar Keycard A",
                  "Hangar Keycard B",
                  "Old Building Key",
                  "Tanker Keycard A",
                  "Tanker Keycard B",
                  "Sky Emblem",
                  "Earth Emblem",
                  "Sea Emblem",
                  "Shaman Slate",
                  "Warrior Slate",
                  "Beast Slate",
                  "Raptor Slate",
                  "Crane Keycard",
                  "Guard's Key"},
         "keys": {"Shaman Slate",
                  "Warrior Slate",
                  "Beast Slate",
                  "Raptor Slate"},
      "emblems": {"Sky Emblem",
                  "Earth Emblem",
                  "Sea Emblem"},
}