from typing import TypedDict, List
from .Regions import Chapters


class LocationDict(TypedDict):
    name: str
    chapter: Chapters
    arc_file: str
    unique_id: str


class EventDict(TypedDict):
    name: str
    chapter: str
    item: str


# Make a unique ID for each location generated like the following "Chapter, Line of ItemID, ItemType" so "115_426_3" would mean "Arc File 115, Line 426", ItemType 3 for briefcase.
# The reason the unique ID includes the Arc file number at the beginning is in case there is somehow an overlap in line/filetype in another file. If s115 has 426_3, and s100 also has 426_3, the arc randomizer wouldn't know the differece otherwise, so it's there as backup.
# Gonna need to make the apworld generate a json on generation that outputs a Location, Arc file, Which line to replace, and what item ID.
# Heres an example for Chapter 1-1 M92F Briefcase being replaced with a green herb;
# [
# "s115.arc", 426, 769, 3
# ]
# This is saying to the Arc Randomizer "Unpack s115.arc, in the item lot xml file go to line 426, replace the itemid value with 769 to place a green herb there, ensure itemtype for that same classref is 3 since it's in a briefcase location.
# Each line in this output json would denote a different item, as pulled from Archipelago's slot data (probably).
location_table: List[LocationDict] = [
    # Chapter 1-1
    {'name': "1-1 M92F Briefcase",
        'chapter': c11_alley1,
        'arc_file': "s115.arc",
        'unique_id': "115_426_3"},
    {'name': "1-1 Butcher Shop Crate",
        'chapter': c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_96_2"},
    {'name': "1-1 Butcher Shop Barrel",
         'chapter': c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_151_2"},
    {'name': "1-1 Carcass House Barrel 1",
         'chapter': c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_206_2"},
    {'name': "1-1 Carcass House Barrel 2",
         'chapter': c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_481_2"},
    {'name': "1-1 Carcass House Box",
         'chapter': c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_41_2"},
    {'name': "1-1 Carcass House Shelf Herb",
         'chapter': c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_316_0"},
    {'name': "1-1 Handgun Ammo after First Zombie",
         'chapter': c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_41_4"},
    {'name': "1-1 Barricade Safehouse Shelf Herb",
         'chapter': c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_206_0"},
    {'name': "1-1 Barricade Safehouse Shelf Grenade",
         'chapter': c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_536_0"},
    {'name': "1-1 Barricade Safehouse Shelf Handgun Ammo",
         'chapter': c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_261_0"},
# Locations are missing valid unique_id that would allow randomization. Basically I can't find out how to assign unique numbers to them cause of how the arc file lays out breakables.
#    {'name': "1-1 Barricade Safehouse Barrel 1",
#         'chapter': c11_alley2,
#         'arc_file': "s116.arc",
#         'unique_id': "116_"},
#    {'name': "1-1 Barricade Safehouse Barrel 2",
#         'chapter': c11_alley2,
#         'arc_file': "s116.arc",
#         'unique_id': "116_"},
#    {'name': "1-1 Barricade Safehouse Barrel 3",
#         'chapter': c11_alley2,
#         'arc_file': "s116.arc",
#         'unique_id': "116_"},
    {'name': "1-1 After Tunnel Shelf Handgun Ammo",
         'chapter': c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_426_0"},
# Two handgun ammos side by side, but not enough appearances of Handgun Ammo in the arc file. Might be a shared location?
#    {'name': "1-1 After Tunnel Shelf Handgun Ammo 2",
#         'chapter': c11_alley2,
#         'arc_file': "s116.arc",
#         'unique_id': "116_"},
    {'name': "1-1 After Tunnel Shelf Herb",
         'chapter': c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_151_0"},
    {'name': "1-1 VZ61 Briefcase",
         'chapter': c11_assembly,
         'arc_file': "s114.arc",
         'unique_id': "114_96_3"},
    {'name': "1-1 Executioner Gold Ring",
         'chapter': c11_assembly,
         'arc_file': "s114.arc",
         'unique_id': "114_41_4"},
    # Chapter 1-2
    {'name': "1-2 Old Building Key",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_41_0"},
    {'name': "1-2 Handgun Ammo on Shelf",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_96_0"},
    {'name': "1-2 Old Building Key",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_41_0"},
    {'name': "1-2 First Aid Spray on Shelf",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_151_0"},
    {'name': "1-2 Antique Clock Chest",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_206_0"},
    {'name': "1-2 Ithaca M37",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_260_0"},
    {'name': "1-2 Handgun Ammo near Allyson",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_513_2"},
    {'name': "1-2 Incendiary Grenade Box",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_371_2"},
    {'name': "1-2 Locked Building Shotgun Ammo",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_426_0"},
    {'name': "1-2 Small Gold Near Allyson",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_481_0"},
    {'name': "1-2 Large Gold Near Allyson",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_536_0"},
    {'name': "1-2 Ivory Relief from Allyson",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_591_1"},
    {'name': "1-2 MG Ammo on Shelf near Allyson",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_646_0"},
    {'name': "1-2 Hand Grenade on Shelf",
         'chapter': c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_701_0"}, 
    {'name': "1-2 Furnace Key",
         'chapter': c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_41_0"}, 
    {'name': "1-2 Furnace Room Herb",
         'chapter': c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_96_0"},
    {'name': "1-2 HG Ammo Case 1",
         'chapter': c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_151_0"},
    {'name': "1-2 HG Ammo Case 2",
         'chapter': c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_206_0"},
    {'name': "1-2 HG Ammo Case 3",
         'chapter': c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_261_0"},
    {'name': "1-2 HG Ammo Case 3",
         'chapter': c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_261_0"},    
    {'name': "1-2 Gold Ring from Uroboros",
         'chapter': c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_316_1"},
    {'name': "2-1 H&K MP5 Briefcase",
         'chapter': c21_storage,
         'arc_file': "s118.arc",
         'unique_id': "118_282_3"},
    {'name': "2-1 Chest Item 1",
         'chapter': c21_storage,
         'arc_file': "s118.arc",
         'unique_id': "118_41_3"},
    {'name': "2-1 Chest Item 2",
         'chapter': c21_storage,
         'arc_file': "s118.arc",
         'unique_id': "118_96_3"},
    {'name': "2-1 Chest Item 3",
         'chapter': c21_storage,
         'arc_file': "s118.arc",
         'unique_id': "118_151_3"},
    {'name': "2-1 First Aid Spray Crate",
         'chapter': c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_96_2"}, 
    {'name': "2-1 Early Green Herb",
         'chapter': c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_96_2"}, 
    {'name': "2-1 HG Ammo in Shipping Container",
         'chapter': c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_151_0"}, 
    {'name': "2-1 Red Herb near Fat Man",
         'chapter': c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_206_0"}, 
    {'name': "2-1 Jewel Bangle from Fat Man",
         'chapter': c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_1060_1"},         
# Where is the port?
# There are definitely items in the port
# This is what I get for trusting a program to rip items out of a file for me.
# Welp, that's a problem for future me.
# TO-DO: Add items from c21_port       
    {'name': "2-1 Alleyway Green Herb",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_41_0"},
    {'name': "2-1 Behind Building Green Herb",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_96_0"},
    {'name': "2-1 Inside Building Green Herb",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_151_0"},
    {'name': "2-1 HG Ammo atop Assist Ladder 1",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_206_0"},
    {'name': "2-1 HG Ammo atop Assist Ladder 2",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_261_0"},
#    {'name': "2-1 HG Ammo",              # Unknown location
#         'chapter': c21_shanty,
#         'arc_file': "s105.arc",
#         'unique_id': "105_371_0"},
#    {'name': "2-1 HG Ammo",              # Unknown location
#         'chapter': c21_shanty,
#         'arc_file': "s105.arc",
#         'unique_id': "105_371_0"},
#    {'name': "2-1 HG Ammo",              # Unknown location
#        'chapter': c21_shanty,
#         'arc_file': "s105.arc",
#         'unique_id': "105_1141_0"},
    {'name': "2-1 Grenades near Sofa 1",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_426_0"},
    {'name': "2-1 Grenades near Sofa 2",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_481_0"},
    {'name': "2-1 Grenades near Sofa 3",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_536_0"},
    {'name': "2-1 Guard's Key",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_646_0"},
#    {'name': "2-1 Large Gold Bars",      # No idea where this location specifically is at.
#         'chapter': c21_shanty,
#         'arc_file': "s105.arc",
#         'unique_id': "105_701_0"},
    {'name': "2-1 Guard's Treasure Chest 1",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_1031_2"},
    {'name': "2-1 Guard's Treasure Chest 2",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_866_2"},
    {'name': "2-1 Guard's Treasure Chest 3",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_921_2"},
    {'name': "2-1 Guard's Treasure Chest 4",
         'chapter': c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_976_2"},