from typing import TypedDict, List
from .Regions import Chapters
from .Options import RE5Options, ExcludeDriving


class LocationDict(TypedDict):
    name: str
    chapter: Chapters
    arc_file: str
    unique_id: str


class EventDict(TypedDict):
    name: str
    chapter: str
    item: str

base_id = 6761000

# Make a unique ID for each location generated like the following "Chapter, Line of ItemID, ItemType" so "115_426_3" would mean "Arc File 115, Line 426", ItemType 3 for briefcase.
# The reason the unique ID includes the Arc file number at the beginning is in case there is somehow an overlap in line/filetype in another file. If s115 has 426_3, and s100 also has 426_3, the arc randomizer wouldn't know the difference otherwise, so it's there as backup.
# Need to make the apworld generate a json on generation that outputs a Location, Arc file, Which line to replace, and what item ID.
# Heres an example for Chapter 1-1 M92F Briefcase being replaced with a green herb;
# [
# "s115.arc", 426, 769, 3
# ]
# This is saying to the Arc Randomizer "Unpack s115.arc, in the item lot xml file go to line 426, replace the itemid value with 769 to place a green herb there, ensure itemtype for that same classref is 3 since it's in a briefcase location.
# Each line in this output json would denote a different item, as pulled from Archipelago's slot data (probably).
location_table: List[LocationDict] = [
    # Chapter 1-1
    {'name': "1-1 M92F Briefcase",
        'chapter': Chapters.c11_alley1,
        'arc_file': "s115.arc",
        'unique_id': "115_426"},
    {'name': "1-1 Butcher Shop Crate",
        'chapter': Chapters.c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_96"},
    {'name': "1-1 Butcher Shop Barrel",
         'chapter': Chapters.c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_151"},
    {'name': "1-1 Carcass House Barrel 1",
         'chapter': Chapters.c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_206"},
    {'name': "1-1 Carcass House Barrel 2",
         'chapter': Chapters.c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_481"},
    {'name': "1-1 Carcass House Box",
         'chapter': Chapters.c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_41"},
    {'name': "1-1 Carcass House Shelf Herb",
         'chapter': Chapters.c11_alley1,
         'arc_file': "s115.arc",
         'unique_id': "115_316"},
    {'name': "1-1 Handgun Ammo after First Zombie",
         'chapter': Chapters.c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_41"},
    {'name': "1-1 Barricade Safehouse Shelf Herb",
         'chapter': Chapters.c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_206"},
    {'name': "1-1 Barricade Safehouse Shelf Grenade",
         'chapter': Chapters.c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_536"},
    {'name': "1-1 Barricade Safehouse Shelf Handgun Ammo",
         'chapter': Chapters.c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_261"},
# Locations are missing valid unique_id that would allow randomization. Basically I can't find out how to assign unique numbers to them cause of how the arc file lays out breakables.
#    {'name': "1-1 Barricade Safehouse Barrel 1",
#         'chapter': Chapters.c11_alley2,
#         'arc_file': "s116.arc",
#         'unique_id': "116_"},
#    {'name': "1-1 Barricade Safehouse Barrel 2",
#         'chapter': Chapters.c11_alley2,
#         'arc_file': "s116.arc",
#         'unique_id': "116_"},
#    {'name': "1-1 Barricade Safehouse Barrel 3",
#         'chapter': Chapters.c11_alley2,
#         'arc_file': "s116.arc",
#         'unique_id': "116_"},
    {'name': "1-1 After Tunnel Shelf Handgun Ammo",
         'chapter': Chapters.c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_426"},
# Two handgun ammos side by side, but not enough appearances of Handgun Ammo in the arc file. Might be a shared location?
#    {'name': "1-1 After Tunnel Shelf Handgun Ammo 2",
#         'chapter': Chapters.c11_alley2,
#         'arc_file': "s116.arc",
#         'unique_id': "116_"},
    {'name': "1-1 After Tunnel Shelf Herb",
         'chapter': Chapters.c11_alley2,
         'arc_file': "s116.arc",
         'unique_id': "116_151"},
    {'name': "1-1 VZ61 Briefcase",
         'chapter': Chapters.c11_assembly,
         'arc_file': "s114.arc",
         'unique_id': "114_96"},
    {'name': "1-1 Executioner Gold Ring",
         'chapter': Chapters.c11_assembly,
         'arc_file': "s114.arc",
         'unique_id': "114_41"},
    # Chapter 1-2
    {'name': "1-2 Old Building Key",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_41"},
    {'name': "1-2 Handgun Ammo on Shelf",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_96"},
    {'name': "1-2 First Aid Spray on Shelf",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_151"},
    {'name': "1-2 Antique Clock Chest",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_206"},
    {'name': "1-2 Ithaca M37",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_261"},
    {'name': "1-2 Handgun Ammo near Allyson",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_316"},
    {'name': "1-2 Incendiary Grenade near Allyson",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_371"},
    {'name': "1-2 Locked Building Shotgun Ammo",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_426"},
    {'name': "1-2 Small Gold Near Allyson",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_481"},
    {'name': "1-2 Large Gold Near Allyson",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_536"},
    {'name': "1-2 Ivory Relief from Allyson",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_591"},
    {'name': "1-2 MG Ammo on Shelf near Allyson",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_646"},
    {'name': "1-2 Hand Grenade on Shelf",
         'chapter': Chapters.c12_urban,
         'arc_file': "s102.arc",
         'unique_id': "102_701"},
    {'name': "1-2 Furnace Key",
         'chapter': Chapters.c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_41"},
    {'name': "1-2 Furnace Room Herb",
         'chapter': Chapters.c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_96"},
    {'name': "1-2 HG Ammo Case 1",
         'chapter': Chapters.c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_151"},
    {'name': "1-2 HG Ammo Case 2",
         'chapter': Chapters.c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_206"},
    {'name': "1-2 HG Ammo Case 3",
         'chapter': Chapters.c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_261"},
    {'name': "1-2 HG Ammo Case 3",
         'chapter': Chapters.c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_261"},
    {'name': "1-2 Gold Ring from Uroboros",
         'chapter': Chapters.c12_furnace,
         'arc_file': "s103.arc",
         'unique_id': "103_316"},
    {'name': "2-1 H&K MP5 Briefcase",
         'chapter': Chapters.c21_storage,
         'arc_file': "s118.arc",
         'unique_id': "118_316"},
    {'name': "2-1 Chest Item 1",
         'chapter': Chapters.c21_storage,
         'arc_file': "s118.arc",
         'unique_id': "118_41"},
    {'name': "2-1 Chest Item 2",
         'chapter': Chapters.c21_storage,
         'arc_file': "s118.arc",
         'unique_id': "118_96"},
    {'name': "2-1 Chest Item 3",
         'chapter': Chapters.c21_storage,
         'arc_file': "s118.arc",
         'unique_id': "118_151"},
    {'name': "2-1 First Aid Spray Crate",
         'chapter': Chapters.c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_96"},
    {'name': "2-1 Early Green Herb",
         'chapter': Chapters.c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_96"},
    {'name': "2-1 HG Ammo in Shipping Container",
         'chapter': Chapters.c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_151"},
    {'name': "2-1 Red Herb near Fat Man",
         'chapter': Chapters.c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_206"},
    {'name': "2-1 Jewel Bangle from Fat Man",
         'chapter': Chapters.c21_bridge,
         'arc_file': "s104.arc",
         'unique_id': "104_261"},
# Where is the port?
# There are definitely items in the port
# This is what I get for trusting a program to rip items out of a file for me.
# Welp, that's a problem for future me.
# TO-DO: Add items from c21_port       
    {'name': "2-1 Alleyway Green Herb",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_41"},
    {'name': "2-1 Behind Building Green Herb",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_96"},
    {'name': "2-1 Inside Building Green Herb",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_151"},
    {'name': "2-1 HG Ammo atop Assist Ladder 1",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_206"},
    {'name': "2-1 HG Ammo atop Assist Ladder 2",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_261"},
#    {'name': "2-1 HG Ammo",              # Unknown location
#         'chapter': Chapters.c21_shanty,
#         'arc_file': "s105.arc",
#         'unique_id': "105_371"},
#    {'name': "2-1 HG Ammo",              # Unknown location
#         'chapter': Chapters.c21_shanty,
#         'arc_file': "s105.arc",
#         'unique_id': "105_371"},
#    {'name': "2-1 HG Ammo",              # Unknown location
#        'chapter': Chapters.c21_shanty,
#         'arc_file': "s105.arc",
#         'unique_id': "105_1141"},
    {'name': "2-1 Grenades near Sofa 1",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_426"},
    {'name': "2-1 Grenades near Sofa 2",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_481"},
    {'name': "2-1 Grenades near Sofa 3",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_536"},
    {'name': "2-1 Guard's Key",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_646"},
#    {'name': "2-1 Large Gold Bars",      # No idea where this location specifically is at.
#         'chapter': Chapters.c21_shanty,
#         'arc_file': "s105.arc",
#         'unique_id': "105_701_0"},
    {'name': "2-1 Guard's Treasure Chest 1",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_1031"},
    {'name': "2-1 Guard's Treasure Chest 2",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_866"},
    {'name': "2-1 Guard's Treasure Chest 3",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_921"},
    {'name': "2-1 Guard's Treasure Chest 4",
         'chapter': Chapters.c21_shanty,
         'arc_file': "s105.arc",
         'unique_id': "105_976"},
    {'name': "2-2 Green Herb Near Train",
         'chapter': Chapters.c22_station,
         'arc_file': "s119.arc",
         'unique_id': "119_41"},
    {'name': "2-2 Green Herb Near Train",
         'chapter': Chapters.c22_station,
         'arc_file': "s119.arc",
         'unique_id': "119_41"},
    {'name': "2-2 Green Herb Near Dogs",
         'chapter': Chapters.c22_station,
         'arc_file': "s119.arc",
         'unique_id': "119_496"},
    {'name': "2-2 HG Ammo on Top of Train",
         'chapter': Chapters.c22_station,
         'arc_file': "s119.arc",
         'unique_id': "119_151"},
    {'name': "2-2 MG Ammo on Top of Train",
         'chapter': Chapters.c22_station,
         'arc_file': "s119.arc",
         'unique_id': "119_206"},
#    {'name': "2-2 Jewel Beetle on Tree", # Where is this 2nd beetle at?
#         'chapter': Chapters.c22_station,
#         'arc_file': "s119.arc",
#         'unique_id': "119_261"},
    {'name': "2-2 Large Gold Pile 1",
         'chapter': Chapters.c22_station,
         'arc_file': "s119.arc",
         'unique_id': "119_316"},
    {'name': "2-2 Large Gold Pile 2",
         'chapter': Chapters.c22_station,
         'arc_file': "s119.arc",
         'unique_id': "119_371"},        
#    {'name': "2-2 Lantern", # Okay I know we can, but PLEASE DON'T.
#         'chapter': Chapters.c22_mines,
#         'arc_file': "s107.arc",
#         'unique_id': "107_41"},
    {'name': "2-2 Red Herb in Mine",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_96"},
    {'name': "2-2 HG Ammo in Mine",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_151"},
    {'name': "2-2 Flash Grenade in Mine",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_206"},
    {'name': "2-2 Green Herb in Mine 1",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_261"},
    {'name': "2-2 Green Herb in Mine 2",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_316"},
    {'name': "2-2 Diamond in Mines Chest",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_261"},
    {'name': "2-2 Diamond in Mines Chest",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_371"},
    {'name': "2-2 Ruby Pear in Quarry 1",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_426"},
    {'name': "2-2 Ruby Pear in Quarry 2",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_481"},
    {'name': "2-2 Ruby Pear in Quarry 3",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_536"},
    {'name': "2-2 Ruby Square on Quarry Central Wheel",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_591"},
    {'name': "2-2 Ruby Square in Quarry Sidepath",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_646"},
    {'name': "2-2 Flash Grenade in Quarry 1",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_701"},
    {'name': "2-2 Flash Grenade in Quarry 2",
         'chapter': Chapters.c22_mines,
         'arc_file': "s107.arc",
         'unique_id': "107_756"},
    {'name': "2-2 HG Ammo in Irving Building 1",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_41"},
    {'name': "2-2 HG Ammo in Irving Building 2",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_96"},
    {'name': "2-2 HG Ammo in Irving Building 3",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_151"},
    {'name': "2-2 HG Ammo before Popokarimu",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_206"},
    {'name': "2-2 Green Herb near SVD Locker",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_261"},
    {'name': "2-2 Green Herb on Table before Popokarimu",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_261"},
    {'name': "2-2 Red Herb",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_316"},
    {'name': "2-2 Hand Grenade 1",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_371"},
    {'name': "2-2 Hand Grenade 2",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_426"},
    {'name': "2-2 Hand Grenade 3",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_481"},
    {'name': "2-2 Proximity Bomb 1",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_536"},
    {'name': "2-2 Proximity Bomb 2",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_591"},
    {'name': "2-2 Proximity Bomb 3",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_646"},
    {'name': "2-2 Unknown Green Herb 1",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_701"},
    {'name': "2-2 Proximity Bomb 4",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_976"},
    {'name': "2-2 Proximity Bomb 5",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1031"},
    {'name': "2-2 Proximity Bomb 6",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1086"},
    {'name': "2-2 MG Ammo",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1141"},
    {'name': "2-2 SG Ammo",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1196"},
    {'name': "2-2 Unknown Green Herb 2",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1251"},
    {'name': "2-2 Dragunov SVD Locker",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1306"},
    {'name': "2-2 Rifle Ammo",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1361"},
    {'name': "2-2 Diamond Brilliant Chest near Turret Truck",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1416"},
    {'name': "2-2 Diamond Pear Ladder near Toilet",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1471"},
    {'name': "2-2 Diamond Square from Booster Ladder",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1526"},
    {'name': "2-2 Unknown Green Herb 3",
         'chapter': Chapters.c22_popokarimu,
         'arc_file': "s108.arc",
         'unique_id': "108_1691"},
    {'name': "3-1 Shaman Slate",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_41"},
#    {'name': "3-1 Shaman Slate", # Second Occurence of Shaman Slate
#         'chapter': Chapters.c31_marsh,
#         'arc_file': "s200.arc",
#         'unique_id': "200_41"},
    {'name': "3-1 Raptor Slate",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_96"},
#    {'name': "3-1 Raptor Slate", # Second Occurence of Raptor Slate
#         'chapter': Chapters.c31_marsh,
#         'arc_file': "s200.arc",
#         'unique_id': "200_206"},
    {'name': "3-1 Green Herb",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_261"},
    {'name': "3-1 Unknown Silver Idol 1",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_316"},
    {'name': "3-1 Unknown Silver Chalice 1",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_371"},
    {'name': "3-1 Ruby Pear in Mask",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_426"},
    {'name': "3-1 Marsh Brown Beetle 1",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_481"},
    {'name': "3-1 Unknown Silver Chalice 2",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_536"},
    {'name': "3-1 H&K P8 Location which is supposed to be a shop item so if you manage to find this please let me know what it is or if I just really found the shop on accident kthx have a good randomizer",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_646"},
    {'name': "3-1 Unknown Silver Idol 2",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_811"},
    {'name': "3-1 Warrior Slate",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_866"},
#    {'name': "3-1 Warrior Slate", # Second occurence of Warrior Slate
#         'chapter': Chapters.c31_marsh,
#         'arc_file': "s200.arc",
#         'unique_id': "200_921"}, 
    {'name': "3-1 Beast Slate",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_976"},
#    {'name': "3-1 Beast Slate", # Second occurence of Beast Slate
#         'chapter': Chapters.c31_marsh,
#         'arc_file': "s200.arc",
#         'unique_id': "200_1031"}, 
    {'name': "3-1 Marsh Brown Beetle 2",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1141"},
    {'name': "3-1 White Egg near Chickens 1",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1196"},
    {'name': "3-1 White Egg near Chickens 2",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1251"},
    {'name': "3-1 White Egg near Chickens 3",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1306"},
    {'name': "3-1 Small Gold",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1361"},
    {'name': "3-1 Brown Beetle near Chickens",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1416"},
    {'name': "3-1 Ruby in Mask near Chickens",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1581"},
    {'name': "3-1 Emerald Pear Somewhere",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1636"},
    {'name': "3-1 Topaz Square Somewhere",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1691"},
    {'name': "3-1 Single-Use Rocket Launcher Briefcase",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1746"},
    {'name': "3-1 HG Ammo on Boat",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1911"},
    {'name': "3-1 MG Ammo 1",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_1966"},
    {'name': "3-1 HG Ammo 1",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_2021"},
    {'name': "3-1 Rifle Ammo 1",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_2076"},
    {'name': "3-1 Unknown Green Herb 2",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_2076"},
    {'name': "3-1 Marsh Brown Beetle 3",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_2186"},
    {'name': "3-1 Ruby in Mask above Altar",
         'chapter': Chapters.c31_marsh,
         'arc_file': "s200.arc",
         'unique_id': "200_2241"},
    {'name': "3-1 HG Ammo Village",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_41"},
    {'name': "3-1 Red Herb Village 1",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_96"},
    {'name': "3-1 Green Herb Herb Village 1", # beyond barricaded door?
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_151"},
    {'name': "3-1 Green Herb Herb Village 2", # beyond barricaded door?
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_206"},
    {'name': "3-1 Red Herb Village 2",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_261"},
    {'name': "3-1 Small Gold Village 1",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_316"},
    {'name': "3-1 Ceremonial Mask in Cave Beyond Barricaded Door",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_371"},
    {'name': "3-1 Small Gold Village 2",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_426"},
    {'name': "3-1 Ladder House Incendiary Grenade",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_481"},
    {'name': "3-1 Ladder House MAG Ammo 1",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_536"},
    {'name': "3-1 Ladder House MAG Ammo 2",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_591"},
    {'name': "3-1 Ladder House Rifle Ammo",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_646"},
    {'name': "3-1 S&2 M29",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_701"},
    {'name': "3-1 Giant Majini Blue Enigma",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_811"},
    {'name': "3-1 Green Herb Beyond Barricaded Door 1",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_921"},
    {'name': "3-1 Green Herb Beyond Barricaded Door 2",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_976"},
    {'name': "3-1 Jewel Beetle Near Bridge Crank",
         'chapter': Chapters.c31_village,
         'arc_file': "s202.arc",
         'unique_id': "202_1031"},
]


event_table: List[EventDict] = [
    {'name': "Chapter 1-1 Complete",
        'chapter': Chapters.c11_assembly,
        'item': "Chapter 1-1 Complete"},
    {'name': "Chapter 1-2 Complete",
        'chapter': Chapters.c12_furnace,
        'item': "Chapter 1-2 Complete"},
    {'name': "Chapter 2-1 Complete",
        'chapter': Chapters.c21_train,
        'item': "Chapter 2-1 Complete"},
    {'name': "Chapter 2-2 Complete",
        'chapter': Chapters.c22_popokarimu,
        'item': "Chapter 2-2 Complete"},
    {'name': "Chapter 3-1 Complete",
        'chapter': Chapters.c31_village,
        'item': "Chapter 3-1 Complete"},
    {'name': "Chapter 3-2 Complete",
        'chapter': Chapters.c32_docks,
        'item': "Chapter 3-2 Complete"},
    {'name': "Chapter 3-3 Complete",
        'chapter': Chapters.c33_irving,
        'item': "Chapter 3-3 Complete"},
    {'name': "Chapter 4-1 Complete",
        'chapter': Chapters.c41_labyrinth,
        'item': "Chapter 4-1 Complete"},
    {'name': "Chapter 4-2 Complete",
        'chapter': Chapters.c42_garden,
        'item': "Chapter 4-2 Complete"},
    {'name': "Chapter 5-1 Complete",
        'chapter': Chapters.c51_u8,
        'item': "Chapter 5-1 Complete"},
    {'name': "Chapter 5-2 Complete",
        'chapter': Chapters.c52_mkono,
        'item': "Chapter 5-2 Complete"},
    {'name': "Chapter 5-3 Complete",
        'chapter': Chapters.c53_jill,
        'item': "Chapter 5-3 Complete"},
    {'name': "Chapter 6-1 Complete",
        'chapter': Chapters.c61_hold,
        'item': "Chapter 6-1 Complete"},
    {'name': "Chapter 6-2 Complete",
        'chapter': Chapters.c62_aheri,
        'item': "Chapter 6-2 Complete"},   
    {'name': "6-3 Defeat Wesker",
        'chapter': Chapters.c63_volcano,
        'item': "Victory"},
]

if not ExcludeDriving == 2:
    event_table.append({
        'name': "Chapter 2-3 Complete",
        'chapter': Chapters.c23_ndesu,
        'item': "Chapter 2-3 Complete"
    })
